# Generated by Django 5.0.3 on 2024-06-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('priority', models.CharField(max_length=10)),
                ('on_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.boardmodel')),
            ],
        ),
    ]
