# Generated by Django 5.0.3 on 2024-06-11 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='performer',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-Do'), ('in-progress', 'В процессе'), ('completed', 'Завершена')], max_length=15),
        ),
    ]
