# Generated by Django 5.0.3 on 2024-06-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_options_alter_taskmodel_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(blank=True, help_text='Формат даты YYYY-MM-DD', null=True, verbose_name='Дедлайн'),
        ),
    ]
