# Generated by Django 5.0.3 on 2024-06-11 22:03

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_taskmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(blank=True, help_text='Формат даты YYYY-MM-DD', null=True, validators=[django.core.validators.MinValueValidator(django.db.models.functions.datetime.Now())], verbose_name='Дедлайн'),
        ),
    ]
