# Generated by Django 5.0.3 on 2024-06-11 22:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_taskmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(blank=True, error_messages=['Дедлайн не может быть раньше сегодняшнего числа'], help_text='Формат даты YYYY-MM-DD', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 12))], verbose_name='Дедлайн'),
        ),
    ]
