# Generated by Django 5.0.6 on 2024-06-15 09:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_taskmodel_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateField(blank=True, help_text='Формат даты YYYY-MM-DD', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2024, 6, 15), message='Дедлайн не может быть раньше сегодняшнего числа')], verbose_name='Дедлайн'),
        ),
    ]
