# Generated by Django 5.0.3 on 2024-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
