# Generated by Django 5.0.3 on 2024-06-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmodel',
            options={'verbose_name': 'Доска проекта', 'verbose_name_plural': 'Доски проектов'},
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='progress',
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_boards', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
