# Generated by Django 5.0.3 on 2024-06-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_boardmodel_deadline_boardmodel_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='priority',
            field=models.CharField(default='low', max_length=10),
            preserve_default=False,
        ),
    ]
