# Generated by Django 5.0.3 on 2024-06-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_boardmodel_options_remove_boardmodel_progress_and_more'),
        ('participation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationmodel',
            options={'verbose_name': 'Участие', 'verbose_name_plural': 'Участия'},
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_in_work', to='boards.boardmodel', verbose_name='Доска проекта'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='can_edit',
            field=models.BooleanField(verbose_name='Права на редактирование'),
        ),
        migrations.AlterField(
            model_name='participationmodel',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
    ]
