# Generated by Django 5.0.6 on 2024-06-11 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_boardmodel_options_remove_boardmodel_progress_and_more'),
        ('participation', '0004_alter_participationmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participationmodel',
            name='Уникальность участия в проекте',
        ),
        migrations.AddConstraint(
            model_name='participationmodel',
            constraint=models.UniqueConstraint(fields=('participant', 'board'), name='Уникальность участия в проекте', violation_error_message='Этот пользователь уже участвует в проекте'),
        ),
    ]
