# Generated by Django 5.0.3 on 2024-03-21 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmodel',
            name='on_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_board', to='boards.boardmodel'),
        ),
    ]
